# iosevka-cadadrish.toml --- my Iosevka font variants

[buildPlans.iosevka-cadadrish-sans]
family = "Iosevka Cadadrish Sans"
spacing = "term"
serifs = "sans"
no-cv-ss = false
no-ligation = true

[buildPlans.iosevka-cadadrish-sans.variants.design]
capital-b = "more-asymmetric-serifless"
capital-j = "descending-serifed-both-sides"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "double-storey-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
k = "cursive-serifless"
l = "tailed"
m = "short-leg-top-left-serifed"
q = "diagonal-tailed"
x = "straight-serifless"
y = "cursive-flat-hook"
z = "straight-serifless-with-horizontal-crossbar"
long-s = "flat-hook-tailed"
eszet = "traditional-flat-hook-tailed"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
zero = "dotted"
one = "base-long-top-serif"
two = "curly-neck"
three = "flattop"
four = "semi-open"
five = "vertical-upper-left-bar"
seven = "straight-crossbar"
asterisk = "hex-low"
paren = "large-contour"
ampersand = "et-toothed"
percent = "rings-continuous-slash-also-connected"
bar = "natural-slope"
lig-ltgteq = "slanted"
